export const REQUEST_PLAYER_INFO = 'REQUEST_PLAYER_INFO';
export const REQUEST_PLAYER_INFO_SUCCESS = 'REQUEST_PLAYER_INFO_SUCCESS';
export const REQUEST_PLAYER_INFO_ERROR = 'REQUEST_PLAYER_INFO_ERROR';

export const REQUEST_PLAYER_TEAM_DATA = 'REQUEST_PLAYER_TEAM_DATA';
export const REQUEST_PLAYER_TEAM_DATA_SUCCESS = 'REQUEST_PLAYER_TEAM_DATA_SUCCESS';
export const REQUEST_PLAYER_TEAM_DATA_ERROR = 'REQUEST_PLAYER_TEAM_DATA_ERROR';
